### ISSUE TITLE
Add new license  CC BY-NC 2.5 and CC BY-NC-SA 3.0

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_nav#100]
Originally requested by @prustar : 

> @acorbi -- i have a document that has a cc license that is not listed : CC BY-NC 2.5
Are the licenses also listed in a reference table in CKAN?
IF so please direct me to it so I can add it - if not please add it.

**Comment by acorbi** [comment]
@prustar the license CC-BY-NC 4.0 is already on the list, you can use this one.

![screenshot from 2018-03-12 11-28-18](https://user-images.githubusercontent.com/384894/37278588-89c2f0b6-25e8-11e8-930f-eceade0706b1.png)

**Comment by prustar** [comment]
@acorbi -- Old documents are listed under old licenses - metadata needs to reflect this. It shouldn't be assumed that the new CC licenses are applicable to these documents pro-rater. If you find documentation of this within the literature then fine but otherwise the metadata needs to reflect the actual license that applies to the document and data. The licenses change in their provisions in each version, this has implications on how information and data can be used. It's important to be clear and transparent about this.
