### ISSUE TITLE
Positioning content

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/ckanext-odm_nav#17]
centering hole contend – left side in one line with tree-icon and logo in header

@media (min-width: 768px)
[role=main], .main {

padding-left: 50px; }

**Comment by acorbi** [comment]
@kathi-aeviator your suggestion is not enough. content should be full-width and responsive for any situation. not just centered for 768px-min wide screens. PR coming...

**Comment by acorbi** [comment]
@kathi-aeviator I have deployed the current status of branch impl-17 which provides an align layout but still not completely full-width and not completely responsive. It is deployed on PP https://pp-data.opendevelopmentmekong.net/

Would be cool if you could come up with a combination of CSS adaptations (as done in other issues) in order to make it decent.

**Comment by kathi-aeviator** [comment]
reviewed it - and agree with that! It's ok for now and we should handle out the responsive things in an other issue! Sorry for confusing! Close issue!
