### ISSUE TITLE
Add options for CC licenses with NC and ND to CKAN

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_nav#85]
Raised originally by @gimmemochi 

@acorbi @prustar I'm not sure if there's a document somewhere describing why we decided to only provide license options we currently have for CKAN record -- I'm wondering whether it's intentional to not list CC licenses with NC and ND on CKAN? Some NGOs publish their publications with CC BY-NC-SA or CC BY-NC-ND. MRLG is an example. See: http://mrlg.org/resources/customary-tenure-in-the-mekong-region-workshop-outcomes/

Should we consider other licenses to be added? 

Consider the [following](https://en.wikipedia.org/wiki/Creative_Commons_license) (except BY and BY-SA which we already have as options)
<img width="581" alt="screen shot 2017-06-08 at 4 48 06 pm" src="https://user-images.githubusercontent.com/6489398/26950052-58f4fe1e-4c6a-11e7-9e89-e33804e5df00.png">

**Comment by acorbi** [comment]
> I'm not sure if there's a document somewhere describing why we decided to only provide license options we currently have for CKAN record

@gimmemochi Very easy. Those variants of CC do not comply with http://opendefinition.org/ and that is why they are not included per default on CKAN. However, in case we want to add them as options we can.

My question would be whether there has been already a case where data entry staff could not upload a record because this option was not available?

**Comment by gimmemochi** [comment]
@acorbi With the exception of content we produce ourself (which is licensed under CC BY SA 4.0) a majority of public domain documentations (I want to say 70% or more) that we aggregated and hosted on our platform do not comply with open definitions. The reason being government, civil society, and even the development partners (with the exception of a few who have been implementing open data) do not publish public domain documents under open definitions. Folks like the MRLG and other civil society organizations, if they apply CC licenses to their content, they would use NC and ND attributions. Law, regulation, and agreement documentations, for example, are not licensed (by default from the publishers) any CC licensing. They are, however, public domain documentations that are accessible to the public. 

If we were to only host content (produced by others) that meets the open definition, we would have a very skinny database now and many years to come. 

Yes, there has already been cases where data entry folks couldn't upload a record because these options aren't available. I found a few records where licensing information have been entered incorrectly. See this example, a [publication by MRLG](https://data.opendevelopmentmekong.net/library_record/recognition-of-customary-tenure-in-the-mekong-region-an-online-dialogue-summary-report-see-more-at-) uploaded by @DBishton.

<img width="1034" alt="screen shot 2017-06-09 at 12 45 11 pm" src="https://user-images.githubusercontent.com/6489398/26985965-b4513526-4d13-11e7-9410-8e8d28263d32.png">
<img width="1036" alt="screen shot 2017-06-09 at 12 45 35 pm" src="https://user-images.githubusercontent.com/6489398/26985969-b86d30ba-4d13-11e7-94c2-4ad9ebedf804.png">

@prustar There must be more records with incorrect licensing info.

**Comment by prustar** [comment]
@gimmemochi  --- **YES** there are loads that are incorrect and continue to be uploaded incorrectly. 
If you recall in **2015** we sent out calls to find data cleaners without success. This is still one of the **major issues with the database** and I cannot control every record consistently as this is very time consuming. We have the two tiered proofing system but all admins can publish their own records if they choose to. We can change this to the **original specifications** that admins must also have their records reviewed by another Admin prior to publication.  @acorbi

**Comment by prustar** [comment]
@acorbi -- YES there has been other cases that Thet raised previously -- in the spreadsheet I created I also included additional open licenses that apply to geospatial data and other types of data specifically. I will try to find this as it's important to have all the options for people to select. It was supposed to have been included in the LibraBase file so that we could update it easily.

**Comment by acorbi** [comment]
@prustar @gimmemochi 

> a majority of public domain documentations (I want to say 70% or more) that we aggregated and hosted on our platform do not comply with open definitions.

Since until now (I just added the CC-BY-NC-4.0, CC-BY-ND-4.0 and CC-BY-NC-ND-4.0 to the list) we did only had OD-compliant licenses, that means that around 70% of the data "aggregated and hosted on our platform" has not been given the proper license
